### ISSUE TITLE
Unicorn UUIDs in MonoToMicroAPIGateway README do not match the Unicorn UUIDs in API

### ISSUE THREAD

**Issue by JasonSarwar** [aws-samples/unishop-monolith-to-microservices#10]
https://github.com/aws-samples/unishop-monolith-to-microservices/tree/master/MonoToMicroAPIGateway

In Steps 3.2.9 and 3.2.13, the uuids in the unicorns field don't match the uuids in my example legacy Unicorns API (uuids are supposed to be unique after all). Maybe the document could tell user to pick one of the uuids from the legacy Unicorns API.

**Comment by deki** [comment]
Hi @JasonSarwar sorry for the late response. We fixed that in the meantime. Please see https://app-modernization.workshop.aws/en/api-gateway/create-methods.html for the updated version.
