### ISSUE TITLE
Cloudformation fails

### ISSUE THREAD

**Issue by SunithaE** [aws-samples/unishop-monolith-to-microservices#16]
Hi,

The cloudformation 'MonoToMicroCF5.json' fails at EC2 instance event. It doesnt show any error messages besides 'Received error for unique id ....'

Are there any prerequisites before i run this ? I tried on us-east-1 and also eu-west-1 
This is based on the workshop - https://app-modernization.workshop.aws

Please advice. 

Thanks!

**Comment by deki** [comment]
Hi Sunitha,
for me the template is working without any problems. Can you please attach a screenshot of the stack events? Do you see any logs in CloudWatch?

**Comment by deki** [comment]
Please also share the EC2 instance console output as described here: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-console.html#instance-console-console-output

**Comment by SunithaE** [comment]
Hi, 

Here is the console output, 




---------------------------------------------------------------

Amazon Linux 2

Kernel 4.14.219-161.340.amzn2.x86_64 on an x86_64

ip-10-0-0-148 login: [   14.854425] cloud-init[2255]: No packages needed for security; 0 packages available
[   14.854738] cloud-init[2255]: No packages marked for update
[   15.307856] cloud-init[2442]: Cloud-init v. 19.3-5.amzn2 running 'modules:final' at Sun, 28 Feb 2021 21:02:55 +0000. Up 15.25 seconds.
[   15.702839] cloud-init[2442]: Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
[   15.914030] cloud-init[2442]: Package aws-cfn-bootstrap-1.4-34.amzn2.noarch already installed and latest version
[   15.915599] cloud-init[2442]: Nothing to do
[  239.256088] cloud-init[2442]: Error occurred during build: Command 4-populate-buckets failed
ci-info: no authorized ssh keys fingerprints found for user ec2-user.
[  239.631055] cloud-init[2442]: ci-info: no authorized ssh keys fingerprints found for user ec2-user.

---------------------------------


It says "Error occurred during build: Command 4-populate-buckets failed"
4-populate-buckets is a cp command from ec2  to S3 bucket. I don't see any files under s3 bucket. 
Could this be because of some missing permissions at EC2 or S3 ?

**Comment by deki** [comment]
Thanks for the details. Please check if you have blocked public access on account level: https://aws.amazon.com/s3/features/block-public-access/
After disabling it, the command should work. I'll add a note to the workshop page.

**Comment by deki** [comment]
@SunithaE Did that solve your problem?

I've also added a note to the instructions.

**Comment by SunithaE** [comment]
Yes blocking public access on account level was the issue. 
Thanks for the prompt help!
