### ISSUE TITLE
Clicking "Products" starts an error loop in the Javascript console

### ISSUE THREAD

**Issue by rottama** [aws-samples/unishop-monolith-to-microservices#17]
The workshop instructions require the user to act with the Javascript console. When they click on "Products" in the top navigation bar by chance, this starts an infinite error loop. This makes it cumbersome to follow the instructions.

![error_loop](https://user-images.githubusercontent.com/77901727/121703589-4a656000-cad3-11eb-8b67-5c61e1707524.JPG)

**Comment by deki** [comment]
Thanks for reporting the issue. I was able to reproduce it on my end and will work on a fix.

**Comment by deki** [comment]
https://github.com/StartBootstrap/startbootstrap-freelancer moved to anime.js in the meantime. I back ported this fix: https://github.com/deki/unishop-monolith-to-microservices/tree/17-easing-fix

We'll review it and merge it afterwards.
