### ISSUE TITLE
The Availability zones are hard coded in the template causing deployment failures. 

### ISSUE THREAD

**Issue by strongjz** [aws-samples/unishop-monolith-to-microservices#2]
The Subnet az are hardcoded in the template when I deployed to us-west-2 the deployment failed since the subnets are hardcoded to us-east-1

**Comment by nirozeri** [comment]
@strongjz yep, known issue, will be addressed shortly. Thanks for the reminder.

**Comment by nirozeri** [comment]
As per @strongjz commit, should be fixed
