### ISSUE TITLE
AWS::S3::Bucket resource "UIBucket" policy does not Public ACLs

### ISSUE THREAD

**Issue by AdrianBegg** [aws-samples/unishop-monolith-to-microservices#38]
The AWS::S3::Bucket resource "UIBucket" in the CloudFormation template does not enable S3 Block Public Access and deploys the bucket with access control lists disabled (due to changes made to S3 defaults starting in April 2023). This causes `An error occurred (AccessControlListNotSupported) when calling the PutObject operation: The bucket does not allow ACLs` to be thrown if front-end components are deployed to the bucket with the grants `--grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers`.

**Comment by deki** [comment]
Thanks for reporting this. As bucket policies are preferred over ACLs we should probably go with the solution proposed in #40.
