### ISSUE TITLE
create failed AWS::S3::BucketPolicy UIBucketPolicy with AccessDenied

### ISSUE THREAD

**Issue by yon666632** [aws-samples/unishop-monolith-to-microservices#47]
When I use CloudFromation template(https://github.com/aws-samples/unishop-monolith-to-microservices/blob/main/MonoToMicroAssets/MonoToMicroCF.yaml), I face error below during creating UIBucketPolicy.

Resource handler returned message: "Access Denied (Service: S3, Status Code: 403, Request ID:XXX, Extended Request ID: XXX" (RequestToken: XXXX, HandlerErrorCode: AccessDenied)
I used Admin

**Comment by deki** [comment]
Can you please check the block public access settings for your account? https://docs.aws.amazon.com/AmazonS3/latest/userguide/configuring-block-public-access-account.html

**Comment by yon666632** [comment]
@deki Thank you, it worked!

**Comment by deki** [comment]
Great, I'm leaving this open until we added a note to the instructions.

**Comment by deki** [comment]
Step added to https://catalog.us-east-1.prod.workshops.aws/workshops/f2c0706c-7192-495f-853c-fd3341db265a/en-US/intro/agenda/deployment
