### ISSUE TITLE
IAM role for Lambda/DynamoDB is not created when DynamoDB is created manually

### ISSUE THREAD

**Issue by bbartlett** [aws-samples/unishop-monolith-to-microservices#6]
The IAM role for Lambda/DynamoDB that is needed for the Lambda microservices in Part 4 is only created in Part 3 if you create the DynamoDB resources using the CloudFormation template. The creation of this role is not included in the manual deployment directions. (This causes the code in Part 4 to fail.)

For anyone needing to manually create this role: Create a new IAM role using the Lambda role type, attach the AWSLambdaBasicExecutionRole managed policy, save the role, then add an inline policy, choose the DynamoDB service, add the access levels GetItem, DeleteItem, PutItem, and UpdateItem, then select the table resource "arn.....:table/unishop".

**Comment by deki** [comment]
Hi @bbartlett sorry for the late response. We fixed that in the meantime. Please see https://app-modernization.workshop.aws/en/microservices/dynamo-db/deploy-dynamo-db-manually.html for the updated version.
