### ISSUE TITLE
Parameters in MonoToMicroCF.Template have no instructions in the read me

### ISSUE THREAD

**Issue by tjbehnken** [aws-samples/unishop-monolith-to-microservices#8]
The readme for Part 1, deploying the monolithic infrastructure, has no parameters listed in the instructions. However, the template for cloudformation defines 2. One, KeyName, needs a key pair, The instructions need to be updated for this. 
If no key pair is present, I get this error:
Parameter KeyName failed to satisfy constraint: must be the name of an existing EC2 KeyPair.

**Comment by nirozeri** [comment]
removed key as shouldn't be used part of the workshop
